import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Button } from "@/components/ui/button";
export const metadata: Metadata = {
  title: "IrfEx Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  const clerkPublicKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
  return (
    
    <ClerkProvider
      publishableKey ={clerkPublicKey}
      signInFallbackRedirectUrl="/Bookings"
    >
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  </ClerkProvider>
    
  )
}
