import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import Image from "next/image";

export const metadata: Metadata = {
  title: "IrfEx Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <header className="h-[50px] p-4 flex items-center bg-slate-100 w-full">
            <SidebarTrigger />
            <Image src={"/irfexlogo.png"} alt="logo" height={80} width={100} />
            </header>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
